### ISSUE TITLE
References db query

### ISSUE THREAD

**Issue by eldoy** [eldoy/skjema#12]
Right now we have this:

```
reference:
    required: true
    type: radio
    source: tag
```

But what if we want to decide the search order? Or limit the search to only this account?

Can be done by checking if source is an object:

```
reference:
    required: true
    type: radio
    source: 
      query:
         # Check if $ has this if contains '.', alternatively can start with $
         account_id: $data.account.id
      sort: 
        created_at: -1
```
