### ISSUE TITLE
Missing for waveorb

### ISSUE THREAD

**Issue by eldoy** [eldoy/skjema#7]
To actually use this without reverting to proper actions, it is necessary to build in more support.

Should all of these be built into schema? Or should we have a merge option with YAML actions?

**Owner validation in waveorb validations**

We need owner, exists and unique validations.

**Filters, flows and setup**

Must be able to call these for each model.

**Validations**

To be able to properly validate, we need validations. It's possible to have them directly in the document, but what happens if you want them to be different for create and update?

```yml
fields:
  email:
    required: true
    validations:
       is: email
       unique: true
   validations_create:
       length: 5
```

Or should validations be moved to bottom? Not inside the field?

```yml
fields:
  email:
    required: true
validations:
  values:
    email:
      is: email
      required: true
validations_create:
  values: 
     email: 
       is: email
```

Or deep?

```yml
fields:
  email:
    required: true
validations:
  all:
    values:
      email:
        is: email
        required: true
  create:
    values: 
      email: 
        is: email
```

Or just move all of this to actions? Not as part of skjema even?

in `actions/model/create`:
```yml
filters: 
validations:
```

Then we might need to revise skjema? At least bring in an `actions: false` option per model?
